SELECT
  PARAMNAME.STRING AS PARAMNAME,
  COUNT(*) AS COUNT
FROM
  DENORM_ENTITIES AS E
  LEFT OUTER JOIN
    ENTITYPARAMETERS AS EP
    ON E.INDEX = EP.ENTITY
  LEFT OUTER JOIN
    DENORM_ENTITIES AS E2
    ON EP.VALUE = E2.INDEX
  LEFT OUTER JOIN
    DESCRIPTORS AS DSP
    ON EP.DESCRIPTOR = DSP.INDEX
  LEFT OUTER JOIN
    STRINGS AS PARAMNAME
    ON DSP.NAME = PARAMNAME.INDEX
WHERE
  E.CATEGORY LIKE 'Walls'
GROUP BY
  PARAMNAME.STRING
ORDER BY

-- select * from denorm_entities where category like '%Tags';
  SELECT E1.CATEGORY    --	e1.LocalId,
  --	e1.GlobalId,
  ,
  E1.INDEX,
  E1.NAME,
  E1.PROJECT_NAME,
  E1.PATH_NAME,
  EP1, DSP
FROM
denorm_entities AS e1
RIGHT OUTER JOIN denorm_points_params AS ep1 ON ep1.Entity = e1.index
LEFT OUTER JOIN denorm_descriptors AS dsp ON dsp."index" = ep1.Descriptor
WHERE
e1.category LIKE '%Tags'
ORDER BY
e1.index;
